spring:
  application:
    name: linshen-dubbo-provider1
server:
  port: 9090
dubbo:
  registry:
    protocol: zookeeper
    address: ip:2181,ip:2182,ip:2183
    id: lin-registry-1
  protocol:
    port: 12345
    name: dubbo
    id: dubbo
    status: server
  application:
    name: linshen-dubbo-provider-name1
    id: linshen-dubbo-provider-id1
    qos-enable: true
    qos-port: 22222
  scan:
    basePackages: com.linshen.dubbo.provider.service
hello:
  service:
    version: 1.0.0
